'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HelpRegistrationInstaller.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was a problem creating Help Shortcut.  The error was: {0}.
        '''</summary>
        Friend ReadOnly Property CreateShortcutErrMsg() As String
            Get
                Return ResourceManager.GetString("CreateShortcutErrMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was a problem deleting Help Shortcut.  The error was: {0}.
        '''</summary>
        Friend ReadOnly Property DeleteShortcutErrMsg() As String
            Get
                Return ResourceManager.GetString("DeleteShortcutErrMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was a problem installing the Intellisense documentation file.  The error was: {0}.
        '''</summary>
        Friend ReadOnly Property FixIntellisenseErrMsg() As String
            Get
                Return ResourceManager.GetString("FixIntellisenseErrMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was a problem launching Help.  The error was: {0}.
        '''</summary>
        Friend ReadOnly Property LaunchHelpErrMsg() As String
            Get
                Return ResourceManager.GetString("LaunchHelpErrMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1033.
        '''</summary>
        Friend ReadOnly Property LocaleFolder() As String
            Get
                Return ResourceManager.GetString("LocaleFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Microsoft Interop Forms Toolkit 2.1.
        '''</summary>
        Friend ReadOnly Property ProductName() As String
            Get
                Return ResourceManager.GetString("ProductName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was a problem registering the Help collection.  The error was: {0}.
        '''</summary>
        Friend ReadOnly Property RegisterHelpErrMsg() As String
            Get
                Return ResourceManager.GetString("RegisterHelpErrMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was a problem registering the sample applications.  The error was: {0}.
        '''</summary>
        Friend ReadOnly Property RegisterSampleErrMsg() As String
            Get
                Return ResourceManager.GetString("RegisterSampleErrMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interop Forms Toolkit 2.1.
        '''</summary>
        Friend ReadOnly Property ShortProductName() As String
            Get
                Return ResourceManager.GetString("ShortProductName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Microsoft Interop Forms Toolkit 2.1 Documentation.lnk.
        '''</summary>
        Friend ReadOnly Property StartMenuLink() As String
            Get
                Return ResourceManager.GetString("StartMenuLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \Programs\Microsoft Visual Basic Power Packs\Interop Forms Toolkit 2.1\.
        '''</summary>
        Friend ReadOnly Property StartMenuRelPathDefault() As String
            Get
                Return ResourceManager.GetString("StartMenuRelPathDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was a problem unregistering the Help collection.  The error was: {0}.
        '''</summary>
        Friend ReadOnly Property UnRegisterHelpErrMsg() As String
            Get
                Return ResourceManager.GetString("UnRegisterHelpErrMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was a problem unregistering the sample applications.  The error was: {0}.
        '''</summary>
        Friend ReadOnly Property UnRegisterSampleErrMsg() As String
            Get
                Return ResourceManager.GetString("UnRegisterSampleErrMsg", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
