'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Microsoft.InteropFormTools

Namespace Interop
    
    <System.Runtime.InteropServices.ClassInterface(Runtime.InteropServices.ClassInterfaceType.AutoDual),  _
     System.Runtime.InteropServices.ComVisible(true)>  _
    Partial Public Class CustomerDetails
        Inherits InteropFormProxyBase
        
        Public Sub New()
            MyBase.New
            FormInstance = New MyCompany.Customers.CustomerDetails()
            RegisterFormInstance()
        End Sub
        
        <System.Diagnostics.DebuggerStepThrough()>  _
        Public Overridable Sub Initialize(ByVal customerID As String)
            UnregisterFormInstance()
            FormInstance = New MyCompany.Customers.CustomerDetails(customerID)
            RegisterFormInstance()
        End Sub
    End Class
End Namespace
