//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSIXInteropFormsToolkit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSIXInteropFormsToolkit.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Creating InteropForm Wrapper Classes for Project {0}.
        /// </summary>
        internal static string ADDIN_STATUS_GENERATED_ERROR_FULL {
            get {
                return ResourceManager.GetString("ADDIN_STATUS_GENERATED_ERROR_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InteropForm Wrapper Classes Generated.
        /// </summary>
        internal static string ADDIN_STATUS_GENERATED_OK {
            get {
                return ResourceManager.GetString("ADDIN_STATUS_GENERATED_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating InteropForm Wrapper Classes....
        /// </summary>
        internal static string ADDIN_STATUS_GENERATING {
            get {
                return ResourceManager.GetString("ADDIN_STATUS_GENERATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InteropForm Wrapper Class Generator.
        /// </summary>
        internal static string DISPLAY_CAPTION {
            get {
                return ResourceManager.GetString("DISPLAY_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {6BB5F8EE-4483-11D3-8BCF-00C04F8EC28C}.
        /// </summary>
        internal static string DOCUMENT_TYPE {
            get {
                return ResourceManager.GetString("DOCUMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event exposes System.EventArgs as part of its signature..
        /// </summary>
        internal static string EVENT_ARGS_COMMENT1 {
            get {
                return ResourceManager.GetString("EVENT_ARGS_COMMENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any dervied types have been cast down..
        /// </summary>
        internal static string EVENT_ARGS_COMMENT2 {
            get {
                return ResourceManager.GetString("EVENT_ARGS_COMMENT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be sure COM client references the Common Language Runtime Library (mscorlib.tlb) or library containing appropriate derived type..
        /// </summary>
        internal static string EVENT_ARGS_COMMENT3 {
            get {
                return ResourceManager.GetString("EVENT_ARGS_COMMENT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event {0} will not be generated. Could not find delegate {1}.  Delegate must be explicitly.
        /// </summary>
        internal static string EventErrMsg {
            get {
                return ResourceManager.GetString("EventErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not supported. Event {1} will not be generated..
        /// </summary>
        internal static string EventErrMsg2 {
            get {
                return ResourceManager.GetString("EventErrMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {6BB5F8EF-4483-11D3-8BCF-00C04F8EC28C}.
        /// </summary>
        internal static string FOLDER_TYPE {
            get {
                return ResourceManager.GetString("FOLDER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not supported. Initialize method for constructor with parameter {1}({2}) will not be generated..
        /// </summary>
        internal static string InitMethodErrMsg {
            get {
                return ResourceManager.GetString("InitMethodErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InteropForm Wrapper Classes.
        /// </summary>
        internal static string INTEROP_FORM_PROXY_FOLDER_NAME {
            get {
                return ResourceManager.GetString("INTEROP_FORM_PROXY_FOLDER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {B5E9BD34-6D3E-4B5D-925E-8A43B79820B4}.
        /// </summary>
        internal static string LanguageCS {
            get {
                return ResourceManager.GetString("LanguageCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {B5E9BD33-6D3E-4B5D-925E-8A43B79820B4}.
        /// </summary>
        internal static string LanguageVB {
            get {
                return ResourceManager.GetString("LanguageVB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating Add-In: could not load supported types for generated code.  .
        /// </summary>
        internal static string LoadSupportedTypesErrMsg {
            get {
                return ResourceManager.GetString("LoadSupportedTypesErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not supported. Method {1} will not be generated..
        /// </summary>
        internal static string MethodErrMsg1 {
            get {
                return ResourceManager.GetString("MethodErrMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not supported. Method {1} will not be generated..
        /// </summary>
        internal static string MethodErrMsg2 {
            get {
                return ResourceManager.GetString("MethodErrMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not supported. Property {1} will not be generated..
        /// </summary>
        internal static string PropertyErrMsg {
            get {
                return ResourceManager.GetString("PropertyErrMsg", resourceCulture);
            }
        }
    }
}
