'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Microsoft.InteropFormTools

Namespace Interop
    
    <System.Runtime.InteropServices.ClassInterface(Runtime.InteropServices.ClassInterfaceType.AutoDual),  _
     System.Runtime.InteropServices.ComVisible(true),  _
     System.Runtime.InteropServices.ComSourceInterfaces(GetType(IHelloWorldFormEventSink))>  _
    Partial Public Class HelloWorldForm
        Inherits InteropFormProxyBase
        
        Public Sub New()
            MyBase.New()
            FormInstance = New MyCompany.HelloWorld.HelloWorldForm()
            RegisterFormInstance()
        End Sub
        
        Public Overridable Property HelloText() As String
            Get
                Dim castFormInstance As MyCompany.HelloWorld.HelloWorldForm = FormInstance
                Return castFormInstance.HelloText
            End Get
            Set
                Dim castFormInstance As MyCompany.HelloWorld.HelloWorldForm = FormInstance
                castFormInstance.HelloText = value
            End Set
        End Property
        
        Public Event SampleEvent As MyCompany.HelloWorld.HelloWorldForm.SampleEventHandler
        
        Public Overloads Overridable Sub Initialize(ByVal helloText As String)
            UnregisterFormInstance()
            FormInstance = New MyCompany.HelloWorld.HelloWorldForm(helloText)
            RegisterFormInstance()
        End Sub
        
        Public Overloads Overridable Sub Initialize(ByVal helloText As String, ByVal repeatTimes As Integer)
            UnregisterFormInstance()
            FormInstance = New MyCompany.HelloWorld.HelloWorldForm(helloText, repeatTimes)
            RegisterFormInstance()
        End Sub
        
        Public Overridable Sub ReverseBackgroundColors()
            Dim castFormInstance As MyCompany.HelloWorld.HelloWorldForm = FormInstance
            castFormInstance.ReverseBackgroundColors()
        End Sub
        
        Protected Overrides Sub HookCustomEvents()
            Dim castFormInstance As MyCompany.HelloWorld.HelloWorldForm = FormInstance
            AddHandler castFormInstance.SampleEvent, AddressOf Me.castFormInstance_SampleEvent
        End Sub
        
        Private Sub castFormInstance_SampleEvent(ByVal sampleEventText As String)
            RaiseEvent SampleEvent(sampleEventText)
        End Sub
    End Class
    
    <System.Runtime.InteropServices.InterfaceTypeAttribute(System.Runtime.InteropServices.ComInterfaceType.InterfaceIsIDispatch),  _
     System.Runtime.InteropServices.ComVisible(true)>  _
    Public Interface IHelloWorldFormEventSink
        
        Sub SampleEvent(ByVal sampleEventText As String)
    End Interface
End Namespace
