'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Microsoft.InteropFormTools

Namespace Interop
    
    <System.Runtime.InteropServices.ClassInterface(Runtime.InteropServices.ClassInterfaceType.AutoDual),  _
     System.Runtime.InteropServices.ComVisible(true),  _
     System.Runtime.InteropServices.ComSourceInterfaces(GetType(IOrderDetailsEventSink))>  _
    Partial Public Class OrderDetails
        Inherits InteropFormProxyBase
        
        Public Sub New()
            MyBase.New
            FormInstance = New MyCompany.Orders.OrderDetails()
            RegisterFormInstance()
        End Sub
        
        Public Event CustomerDetailsRequested As MyCompany.Orders.OrderDetails.CustomerDetailRequestedEventHandler
        
        Public Event ProductDetailsRequested As MyCompany.Orders.OrderDetails.ProductDetailRequestedEventHandler
        
        Protected Overrides Sub HookCustomEvents()
            Dim castFormInstance As MyCompany.Orders.OrderDetails = FormInstance
            AddHandler castFormInstance.CustomerDetailsRequested, AddressOf Me.castFormInstance_CustomerDetailsRequested
            AddHandler castFormInstance.ProductDetailsRequested, AddressOf Me.castFormInstance_ProductDetailsRequested
        End Sub
        
        Private Sub castFormInstance_CustomerDetailsRequested(ByVal customerID As String)
            RaiseEvent CustomerDetailsRequested(customerID)
        End Sub
        
        Private Sub castFormInstance_ProductDetailsRequested(ByVal productID As String)
            RaiseEvent ProductDetailsRequested(productID)
        End Sub
        
        <System.Diagnostics.DebuggerStepThrough()>  _
        Public Overridable Sub Initialize(ByVal orderID As String)
            UnregisterFormInstance()
            FormInstance = New MyCompany.Orders.OrderDetails(orderID)
            RegisterFormInstance()
        End Sub
        
        <System.Diagnostics.DebuggerStepThrough()>  _
        Public Overridable Sub SetOrder(ByVal orderID As String)
            Dim castFormInstance As MyCompany.Orders.OrderDetails = FormInstance
            castFormInstance.SetOrder(orderID)
        End Sub
    End Class
    
    <System.Runtime.InteropServices.InterfaceTypeAttribute(System.Runtime.InteropServices.ComInterfaceType.InterfaceIsIDispatch),  _
     System.Runtime.InteropServices.ComVisible(true)>  _
    Public Interface IOrderDetailsEventSink
        
        Sub CustomerDetailsRequested(ByVal customerID As String)
        
        Sub ProductDetailsRequested(ByVal productID As String)
    End Interface
End Namespace
